# Run H2O AutoML
#
# Part of the project Gradient Boosted Trees and AutoML at https://github.com/gradient-ai/Classical-ML-Example
# Runs same analysis as the Notebook automl_in_h2o.ipynb, but abbreviated code and minimal text
# A model is output that can be deployed, the same as from the Notebook
# This YAML calls automl.py
#
# ### Add dataset creation caveat like StyleGAN2 ###
#
# Last updated: Jul 14th 2021

jobs:

  # Clone GitHub repository

  ### Public version will not need "username:" and "password:" lines with GitHub credentials ###

  CloneRepo:
    resources:
      instance-type: C5
    inputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/Classical-ML-Example
      username: nmb-paperspace
      password: secret:GITHUB_ACCESS_TOKEN

  # Run the analysis

  ClassicalML:
    resources:
      instance-type: P4000
    needs:
      - CloneRepo
    inputs:
      repo:
        type: volume
    outputs:
      modelOutputs:
        type: dataset
        with:
          id: dstro9y6kduxqhl
    uses: script@v1
    with:
      script: |-
        pip install h2o==3.32.1.3
        pip install install-jdk
        cp -R /inputs/repo /classicalml
        cd /classicalml
        python automl.py
      image: tensorflow/tensorflow:2.4.1-gpu-jupyter
