# GBT+AutoML Workflow: Run H2O AutoML
#
# Part of the project Gradient Boosted Trees and AutoML at https://github.com/gradient-ai/Gradient-Boosted-Trees-and-AutoML
# See that URL for instructions on how to use, under "To run the Workflow (advanced)"
#
# Runs the same analysis as the Notebook automl_in_h2o.ipynb, but abbreviated code and minimal text
# A model is output that can be deployed via Java (see the GitHub repository linked above), the same as from the Notebook
# This YAML calls gbt_automl.py
#
# Dataset IDs
#
# The user needs to create their own Gradient managed datasets for job outputs to replace the IDs this file contains:
#
# modelOutputs -> "dsr5kd40ly5uag0"
#
# Last updated: Aug 06th 2021

jobs:

  # Clone GitHub repository

  CloneRepo:
    resources:
      instance-type: C5
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/Gradient-Boosted-Trees-and-AutoML

  # Run the analysis

  GBTAutoML:
    resources:
      instance-type: C5 # Or C7, if it is available to you, which will run about 2x as fast
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      modelOutputs:
        type: dataset
        with:
          ref: dsr5kd40ly5uag0
    uses: script@v1
    with:
      script: |-
        pip install h2o==3.32.1.3
        pip install install-jdk==0.3.0
        cp -R /inputs/repo /gbt_automl
        cd /gbt_automl/Workflow
        python gbt_automl.py
      image: tensorflow/tensorflow:2.4.1-gpu-jupyter
