# Run H2O AutoML
#
# Part of the project Gradient Boosted Trees and AutoML at https://github.com/gradient-ai/Gradient-Boosted-Trees-and-AutoML
# See that URL for instructions on how to use, under "To run the Workflow (advanced)"
#
# Runs same analysis as the Notebook automl_in_h2o.ipynb, but abbreviated code and minimal text
# A model is output that can be deployed, the same as from the Notebook
# This YAML calls automl.py
#
# Dataset IDs
#
# The user needs to create their own Gradient managed datasets for job outputs to replace the IDs this file contains:
#
# modelOutputs -> "dstro9y6kduxqhl"
#
# Last updated: Jul 22nd 2021

jobs:

  # Clone GitHub repository

  CloneRepo:
    resources:
      instance-type: C5
    inputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/gradient-ai/Gradient-Boosted-Trees-and-AutoML

  # Run the analysis

  GBTAutoML:
    resources:
      instance-type: C7
    needs:
      - CloneRepo
    inputs:
      repo:
        type: volume
    outputs:
      modelOutputs:
        type: dataset
        with:
          id: dstro9y6kduxqhl
    uses: script@v1
    with:
      script: |-
        pip install h2o==3.32.1.3
        pip install install-jdk==0.3.0
        cp -R /inputs/repo /gbt_automl
        cd /gbt_automl/Workflow
        python gbt_automl.py
      image: tensorflow/tensorflow:2.4.1-gpu-jupyter
